**Importing Libraries and Dataset**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
dataset=pd.read_csv('data.csv')
X=dataset.iloc[:, 2:-1].values
Y=dataset['diagnosis'].values
Y = Y.reshape(-1,1)

In [ ]:
X.shape

(569, 29)

In [ ]:
Y.shape

(569, 1)

In [ ]:
print(Y)

[['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['B']
 ['B']
 ['B']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['B']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['B']
 ['M']
 ['B']
 ['B']
 ['B']
 ['B']
 ['B']
 ['M']
 ['M']
 ['B']
 ['M']
 ['M']
 ['B']
 ['B']
 ['B']
 ['B']
 ['M']
 ['B']
 ['M']
 ['M']
 ['B']
 ['B']
 ['B']
 ['B']
 ['M']
 ['B']
 ['M']
 ['M']
 ['B']
 ['M']
 ['B']
 ['M']
 ['M']
 ['B']
 ['B']
 ['B']
 ['M']
 ['M']
 ['B']
 ['M']
 ['M']
 ['M']
 ['B']
 ['B']
 ['B']
 ['M']
 ['B']
 ['B']
 ['M']
 ['M']
 ['B']
 ['B']
 ['B']
 ['M']
 ['M']
 ['B']
 ['B']
 ['B']
 ['B']
 ['M']
 ['B']
 ['B']
 ['M']
 ['B']
 ['B']
 ['B']
 ['B']
 ['B']
 ['B']
 ['B']
 ['B']
 ['M']
 ['M']
 ['M']
 ['B']
 ['M']
 ['M']
 ['B']
 ['B']
 ['B']
 ['M']
 ['M']
 ['B']
 ['M']
 ['B']
 ['M']
 ['M']
 ['B']
 ['M']
 ['M']
 ['B']
 ['B']
 ['M']
 ['B']
 ['B']
 ['M']
 ['B']

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Assuming 'y' is your target variable
label_encoder = LabelEncoder()
Y = label_encoder.fit_transform(Y)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
Y.shape

(569,)

In [ ]:
print(Y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0
 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1
 0 1 0 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 1 1 0 0
 0 1 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 1 0 0
 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1
 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 1 0 0
 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 1 0 1 0 0 1 

**Splitting Dataset**

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=0)

In [ ]:
print("X_train:",X_train.shape)
print("Y_train:",Y_train.shape)
print("X_test:",X_test.shape)
print("Y_test:",Y_test.shape)

X_train: (426, 29)
Y_train: (426,)
X_test: (143, 29)
Y_test: (143,)


**Feature Scaling**

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

**--------------------------------------------------------------------------------------------**

**Training  and Testing LR Model**

In [ ]:
from sklearn.linear_model import LogisticRegression
lrobj=LogisticRegression(random_state=0)
lrobj.fit(X_train,Y_train)

LogisticRegression(random_state=0)

In [ ]:
LR_pred=lrobj.predict(X_test)

Training and Testing Naive Bayes Model

In [ ]:
from sklearn.naive_bayes import GaussianNB
gb = GaussianNB()
gb.fit(X_train,Y_train)

GaussianNB()

In [ ]:
NB_pred =  gb.predict(X_test)

**Training and Testing SVM Model**

In [ ]:
from sklearn.svm import SVC
svcobj=SVC(kernel='linear',random_state=0)
svcobj.fit(X_train,Y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
SVC_pred=svcobj.predict(X_test)

**Training and Testing Kernel SVM model**

In [ ]:
from sklearn.svm import SVC
ksvcobj=SVC(kernel='rbf',random_state=0)
ksvcobj.fit(X_train,Y_train)

SVC(random_state=0)

In [ ]:
KSVC_pred=ksvcobj.predict(X_test)

**Training and Testing Naive Bayes Classifier Model**

In [ ]:
from sklearn.naive_bayes import GaussianNB
nbobj=GaussianNB()
nbobj.fit(X_train,Y_train)

GaussianNB()

In [ ]:
NB_pred=nbobj.predict(X_test)

**Training and Testing DTC Model**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtcobj=DecisionTreeClassifier(criterion='entropy',random_state=0)
dtcobj.fit(X_train,Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
DTC_pred=dtcobj.predict(X_test)

**Training and Testing RFC Model**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfcobj=RandomForestClassifier(n_estimators=100,criterion='entropy',random_state=0)
rfcobj.fit(X_train,Y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [ ]:
RFC_pred=rfcobj.predict(X_test)

**Training and Testing K-NN Model**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
kncobj=KNeighborsClassifier()
kncobj.fit(X_train,Y_train)

KNeighborsClassifier()

In [ ]:
KNN_pred=kncobj.predict(X_test)

**--------------------------------------------------------------------------------------------**

**Confusion Matrix for LR Model**

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(Y_test,LR_pred))
accuracy_score(Y_test,LR_pred)

[[86  4]
 [ 4 49]]


0.9440559440559441

Confusion  Matrix for Naive Byes Model


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(Y_test,NB_pred))
accuracy_score(Y_test,NB_pred)

[[85  5]
 [ 6 47]]


0.9230769230769231

**Confusion Matrix for SVM Model**

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(Y_test,SVC_pred))
accuracy_score(Y_test,SVC_pred)

[[87  3]
 [ 2 51]]


0.965034965034965

**Confusion Matrix for Kernel SVM Model**

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(Y_test,KSVC_pred))
accuracy_score(Y_test,KSVC_pred)

[[88  2]
 [ 3 50]]


0.965034965034965

**Confusion Matrix for Naive Bayes Model**

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(Y_test,NB_pred))
accuracy_score(Y_test,NB_pred)

[[85  5]
 [ 6 47]]


0.9230769230769231

**Confusion Matrix for DTC Model**

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(Y_test,DTC_pred))
accuracy_score(Y_test,DTC_pred)

[[84  6]
 [ 1 52]]


0.951048951048951

**Confusion Matrix for RFC Model**

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(Y_test,RFC_pred))
accuracy_score(Y_test,RFC_pred)

[[88  2]
 [ 1 52]]


0.9790209790209791

**Confusion Matrix for KNN Model**

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(Y_test,KNN_pred))
accuracy_score(Y_test,KNN_pred)

[[89  1]
 [ 5 48]]


0.958041958041958